### ISSUE TITLE
fetching all contributors fails on shipkit-bootstrap

### ISSUE THREAD

**Issue by szczepiq** [mockito/shipkit#235]
I found a couple of issues when testing bootstrap scenarios:
 - ~~bad fetch url (2x https :) - "https://api.github.com/repos/http://github.com/mockito/shipkit-bootstrap/contributors?access_token=76826c9ec886612f504d12fd4268b16721c4f85d&per_page=100"~~
 - exception message bug (no value for readOnlyAuthToken): "Problems fetching and parsing contributors from GitHub repo: 'http://github.com/mockito/shipkit-bootstrap', using read only token: 'readOnlyAuthToken'"

### Steps to reproduce

- merge https://github.com/mockito/shipkit-bootstrap/pull/1
- clone "shipkit-bootstrap"
- run "./gradlew build"
- ~~observe failure:~~

```
:fetchAllContributors
  Fetching all contributors for project
  Querying GitHub API for all contributors for project
GET https://api.github.com/repos/http://github.com/mockito/shipkit-bootstrap/contributors?access_token=76826c9ec886612f504d12fd4268b16721c4f85d&per_page=100
:fetchAllContributors FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':fetchAllContributors'.
> Problems fetching and parsing contributors from GitHub repo: 'http://github.com/mockito/shipkit-bootstrap', using read only token: 'readOnlyAuthToken'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

**Comment by mstachniuk** [comment]
I checked it today (shipkit:0.8.87) master branch and there is my output:

```
:fetchAllContributors
  Fetching all contributors for project
  Querying GitHub API for all contributors for project
GET https://api.github.com/repos/mockito/shipkit/contributors?access_token=e7fe8fcfd6ffedac384c8c4c71b2a48e646ed1ab&per_page=100
:fetchAllContributors FAILED
```

GitHub API returns 401, "message": "Bad credentials".
This same request without `access_token` works, but:
1. There should be `shipkit-bootstrap` instead of `shipkit`, I think it comes from: 
https://github.com/mockito/shipkit/blob/63c6046a7dde239347abba118249f657c82451d3/src/main/groovy/org/shipkit/internal/gradle/ReleaseConfigurationPlugin.java#L86
Is that expected behavior?
2. I think in "shipkit-bootstrap" project a file shipkit.gradle should be pre-defined, OR build should fail with info about lack of configuration, OR we should change in shipkit above line and point to shipkit-bootstrap (and shipkit-bootstrap access token).
3. What do you think about a feature with remove `access_token` and try GitHub API call without it, if it's wrong (and log this to the console as Warning)?

**Comment by szczepiq** [comment]
@mstachniuk, thanks a lot for verifying the issue! Indeed it is fixed (blushing :).

>There should be shipkit-bootstrap instead of shipkit, I think it comes from:

Those are essentially dummy values, only used to make the first build pass. We probably want to revisit because they are kind of confusing.

>I think in "shipkit-bootstrap" project a file shipkit.gradle should be pre-defined

Great idea! Please review: https://github.com/mockito/shipkit-bootstrap/pull/2

>What do you think about a feature with remove access_token and try GitHub API call without it, if it's wrong (and log this to the console as Warning)?

What's the use case?

**Comment by szczepiq** [comment]
This ticket can be closed when https://github.com/mockito/shipkit/pull/238 is merged!

**Comment by mstachniuk** [comment]
@szczepiq 
>>What do you think about a feature with remove access_token and try GitHub API call without it, if it's wrong (and log this to the console as Warning)?
>What's the use case?
If user configure wrong access token we can still do calls to GitHub API (without access token) until cross rate limit.

**Comment by mstachniuk** [comment]
Close via https://github.com/mockito/shipkit/pull/238
