### ISSUE TITLE
Hardcoded pull request title and description

### ISSUE THREAD

**Issue by mockitoguy** [mockito/shipkit#368]
## Problem

Our really cool 'org.shipkit.upgrade-downstream' adds and configures CreatePullRequestTask. This task automatically creates pull requests to other projects with version bump. The task implementation [hardcodes pull request](https://github.com/mockito/shipkit/blob/a94f0a12f6070b1ba0be5127dfdab110f66ee154/src/main/groovy/org/shipkit/internal/gradle/versionupgrade/CreatePullRequest.java#L39) 'title' and 'description' values. This makes the task less robust, less configurable. It also ties implementation details with configuration.

## Suggested solution

Let's expose 'title' and 'description' properties on the [CreatePullRequestTask](https://github.com/mockito/shipkit/blob/master/src/main/groovy/org/shipkit/internal/gradle/git/tasks/CloneGitRepositoryTask.java). Ideally, the values of those properties should be configured by the plugin.

This ticket is marked as 'please-contribute'. Please let us know if you have questions on how to get started!

**Comment by ArturSkowronski** [comment]
@szczepiq I would like to take it :)

**Comment by szczepiq** [comment]
@ArturSkowronski, go for it! We don't have a way to assign the ticket in the tracker for non-members. However, consider the ticket yours ;)

**Comment by ArturSkowronski** [comment]
I have one question @szczepiq - do we want to allow users to use some kind of placeholders for dependency version and dependency name in their PR descriptions/titles that would be filled automatically - similar to current solution? Especially the version number would be something that I would like to have filled in title of PR.

Also, I would like to confirm - if somebody don't pass title/description in task configuration, we should fallback to current solution, am I right? As sensible default.

**Comment by wwilk** [comment]
@ArturSkowronski No needs for placeholders or default values. The idea is to make this task more generic, so that it can be reused in other scenarios where creating a pull request would be useful ( example from the top of my head - performing automated migration in downstream projects).

Basically the values of "title" and "body" that are currently set in [task](https://github.com/mockito/shipkit/blob/1ceb2130d06d0ca7a86b52c9239a25bdc5a25d63/src/main/groovy/org/shipkit/internal/gradle/versionupgrade/CreatePullRequest.java), should be set instead in the [plugin](https://github.com/mockito/shipkit/blob/1ceb2130d06d0ca7a86b52c9239a25bdc5a25d63/src/main/groovy/org/shipkit/internal/gradle/versionupgrade/UpgradeDependencyPlugin.java#L193) configuring the task. 

I would throw an exception if "title" and "body" are not set. Task is not really useful without them and I can't think of a sensible defaults.

**Comment by szczepiq** [comment]
+1 to all feedback from @wwilk

>Especially the version number would be something that I would like to have filled in title of PR.

I like this idea! It will make the title+description better, more specific.

**Comment by ArturSkowronski** [comment]
Sorry for lack of response, I was out for few days - family stuff

@szczepiq @wwilk 
About this version number - still I don't know how we can introduce version number in custom title without some kind of placeholder value - IMHP user needs to define where to place this number in title.

Sorry if I'm missing something obvious there.

**Comment by wwilk** [comment]
@szczepiq 
There is already the current version number in PR title (current title = "Version of %s upgraded to %s"). It should be configured the same way, but in plugin instead of task, so that we use it only for this specific use case, not by default. Since there is no sensible default for PR title, I don't think we can use version number there. Or am I missing sth?

**Comment by szczepiq** [comment]
>There is already the current version number in PR title (current title = "Version of %s upgraded to %s")

Great. Ignore my request, then :)

>It should be configured the same way, but in plugin instead of task, so that we use it only for this specific use case, not by default.

Exactly.

>still I don't know how we can introduce version number in custom title without some kind of placeholder value

@ArturSkowronski, we don't need 'custom' PR title. We just want the some extra fields on the task. Basically, instead of hardcoding something inside the method body, we expose a field on a class. This way, the API is richer.

Hope it makes sense now!

**Comment by ArturSkowronski** [comment]
@szczepiq yep, I understand that - I'm only concerned that putting %s in configuration string could be possibly cryptic to end user and would in the end force him to read code to understand what will show up in the PR Title. But probably just an info in docs or sth will be ok :)

**Comment by szczepiq** [comment]
Completing this ticket can help #443. We could customize the pull request message sent from Shipkit to Shipkit to contain "[ci skip-release]".

@ArturSkowronski, are you still interested in working on this? :)

**Comment by szczepiq** [comment]
One more suggestion: I think if we include "[ci skip-release]" string in the PR title, for PRs generated from Shipkit to Shipkit, we will effectively complete #443.

**Comment by ArturSkowronski** [comment]
Yes, sure. I have crazy busy time recently... Will do it today/tomorrow. Sorry for the lag!

**Comment by ArturSkowronski** [comment]
@szczepiq I created PR: https://github.com/mockito/shipkit/pull/474. It is closed for now due to necessary changes from https://github.com/mockito/shipkit-example/pull/109, but I will be grateful for taking a look on implemented solution and of course on PR from shipkit-example :)

**Comment by wwilk** [comment]
Fixed by #474
