### ISSUE TITLE
Better exception message when user forgets to configure GH_WRITE_TOKEN

### ISSUE THREAD

**Issue by mockitoguy** [mockito/shipkit#375]
### Problem

When the user forgets to configure GH_WRITE_TOKEN in Travis CI, the failure on Travis is not very clear:

```
[./gradlew] :gitPush
[./gradlew]   'git push' uses GitHub write token
[./gradlew]   Executing:
[./gradlew]     git push https://github.com/mockito/shipkit-bootstrap.git v0.0.3 master
[./gradlew] :gitPush FAILED
[./gradlew] 
[./gradlew] FAILURE: Build failed with an exception.
[./gradlew] 
[./gradlew] * What went wrong:
[./gradlew] Execution failed for task ':gitPush'.
[./gradlew] 
[./gradlew] > Execution of command failed (exit code 128):
[./gradlew]     git push https://github.com/mockito/shipkit-bootstrap.git v0.0.3 master
[./gradlew]     Captured command output:
[./gradlew]   remote: Invalid username or password.
[./gradlew]   fatal: Authentication failed for 'https://github.com/mockito/shipkit-bootstrap.git/'
```

I bumped into this issue when testing bootstrapping scenarios ([build failure](https://travis-ci.org/mockito/shipkit-bootstrap/builds/268985752)).

### Suggested solution

Instead of letting 'gitPush' fail with generic error, we should write a hint that the problem might be caused by missing or invalid setting of GH_WRITE_TOKEN. To get started, see the implementation of [git push task](https://github.com/mockito/shipkit/blob/master/src/main/groovy/org/shipkit/internal/gradle/git/tasks/GitPush.java#L32). Instead of just letting it fail, we should test return value and emit a warning or different exception.

If you want to take on this ticket, write a comment so that the team knows :) Let us know if you have any questions!

**Comment by ArturSkowronski** [comment]
Hey @mockitoguy , I'd like to take this task :) I hope it won't take me so much time as previous one.

After a talk with @wwilk we found following things to do in this task: 
- Update docs about authorization with GH_WRITE_TOKEN and possible fallback to default git configuration
- Catch exception and check if it's message follow patter containing "Authentication failed"
- In this case, check if GH_WRITE_TOKEN is set and if not, provide hint that this can be possible issue. Otherwise, suggest it can be invalid.

**Comment by mockitoguy** [comment]
Thank you @ArturSkowronski for contributing!

**Comment by ArturSkowronski** [comment]
Thanks for merging @mockitoguy :) I'll add some tests in another PR :)
