### ISSUE TITLE
Introduce kotlin to the project

### ISSUE THREAD

**Issue by StefMa** [mockito/shipkit#453]
I'm a fan of kotlin.
So I wanted to ask how familiar are you guys with that? And if you are familiar can we introduce it to the project? 🤔 

I think it will be bring way more readability to the code.
Since the plugin delivers artifacts no "user" needs to use it as well.
Additional. Currently there is a real hype/run on kotlin. Maybe we can get more contributors to the project if we use it? 🤔 

Of course, there are points against kotlin.
Not all are very familiar with that "new language". If a reviewer can't read/write kotlin it make no sense to review :)

**Comment by wwilk** [comment]
Hi Stefan, there was an idea to use Kotlin a few months ago. I like the advantages, it seems also that Kotlin can be compiled into Java 6 (see https://kotlinlang.org/docs/reference/faq.html#does-kotlin-only-target-java-6), for which we want to have compatibility.

On the other hand what about current Java code? Do we migrate it or it stays? Migration would take a lot of time. If we keep it, it may be even more confusing for newcomers, since we also have a few classes in Groovy. Additionally although I think the fact that Kotlin is hype can bring some new contributors to the project, at the same time it can make it harder for people with Java experience, and according to Tiobe index (https://www.tiobe.com/tiobe-index/) there is probably still much more of them than Kotlin ones.

**Comment by szczepiq** [comment]
Interesting suggestion! I like Kotlin, too.

Here's my feedback:
 - Kotlin can attract some contributors while discouraging others (+1 to @wwilk comment)
 - Learning new language for existing contributors is a distraction from the goals of the project. I think I'd rather us to move to Java 8 first.
 - Kotlin is not yet mature. We don't know yet if the compatibility promises will be kept

Let's keep the ticket open and see if there is more feedback supporting Kotlin. Perhaps in the future we will do it. Thank you for contributing interesting ideas!

**Comment by StefMa** [comment]
> On the other hand what about current Java code? Do we migrate it or it stays?

I would definitely say that it should stay. Kotlin was designed from the ground up to have 100% compatibility with java. So there is really no need to "migrate everything now". 
I would suggest to follow the "step by step" principle.
Just keep the current java files. New classes/files should be developed in Kotlin. If someone have time (or fun) the can convert existing Java implementations into Kotlin (don't use the auto converter. It generates not the optional code) but keep the Java-Tests! So we can make sure that nothing breaks in the implementation.
If the tests is green, we can also convert (if we have time and fun) the tests into kotlin...

> since we also have a few classes in Groovy.

Create a issue that we should convert it to java 😉
We have [Hacktoberfest](https://hacktoberfest.digitalocean.com). Maybe someone will find some time to do it 🙂

> Kotlin can attract some contributors while discouraging others

I think the guys on GitHub are the typical stereotypes. Yep, there are more java devs out there. But I think the most aren't on GitHub which have never seen/touched/interest in Kotlin.
I think it will bring way more contributors that discouraging others... (Just a feeling of course)

> Learning new language for existing contributors is a distraction from the goals of the project

Valid point. That is the reason why I started to mentioned it. The "top maintainer"
 ('szczepiq', 'mstachniuk', 'wwilk', 'epeee', 'NagRock') needs to already know the language. Otherwise it make no sense at this time.

> Kotlin is not yet mature.

Is it not mature? 🤔 Sure? Google just make it to a first class language in Android. Thousands of Apps in the Play Store are already written in Kotlin. Thousands of millions articles pops up each day which says Kotlin is 100% production ready. I haven't seen any article about "the bad sides about kotlin" yet.

> We don't know yet if the compatibility promises will be kept

**Do you mean the java 6 compatibility?**
Similar to above. Google have made Kotlin to a first class language in Android. Android is more or less 100% java 6. I think even if Kotlin isn't interested anymore to support backward compatibility than it will be Google which force JetBrains to do it... IMO
Even if they drop the java 6 support in the future. I think than it is finally time to upgrade shipkit to v6 which drops java 6 as well 😉

**If you mean compatibility with java?**
As I said. Kotlin was designed from the ground to works perfectly hand in hand with java. And you know why? Because all there IDEs are written in Java. They can't (like we) just convert there whole IDE-Java-Classes into Kotlin in one day and say: "ok, mic drop. Kotlin don't support java anymore". That is just not possible...
I think there is another reason why the don't want to drop the java interop support. As @wwilk mentioned. There are way more java devs out there. Which means there are way more **existing** java software than new software (which will be evaluate to written in kotlin).
But if they keep the compatibility they can make sure that Kotlin gets way faster populare...

Oh.. wow. I sound like a Kotlin evangelist 🙃

**Comment by magneticflux-** [comment]
If Groovy is being discouraged on the basis of performance and user-friendliness, Kotlin seems like the next best bet. In fact, Gradle even [recommends](https://docs.gradle.org/current/userguide/custom_plugins.html) plugins to be written in Kotlin instead of Groovy:

> You can implement a Gradle plugin in any language you like, provided the implementation ends up compiled as bytecode. In our examples, we are going to use Groovy as the implementation language. Groovy, Java or Kotlin are all good choices as the language to use to implement a plugin, as the Gradle API has been designed to work well with these languages. In general, a plugin implemented using Java or Kotlin, which are statically typed, will perform better than the same plugin implemented using Groovy.

With regard to learning the language, I read an article (unfortunately I don't have the link immediately available) that talked about how the author's company hired developers for a Kotlin project by only requiring Java knowledge and then remarked that even the hires without any prior Kotlin experience were writing completely idiomatic code within a week. I think Kotlin definitely has the easiest learning curve out of all the JVM languages (at least coming from Java, that is).

As far as tests go, keeping them in Groovy and using Spock seems fine to me. Groovy is a bit slower, but that doesn't matter as much in tests as it does in production. Additionally, my impression of Spock from the few hours I've worked with it so far is very high. I don't know of another testing framework that is as effective as Spock is.

**Comment by mockitoguy** [comment]
I will close this ticket for now. We can always reopen. At this moment, we want to focus on other priorities. Thank you for suggesting!
