### ISSUE TITLE
Releases are making tags unexpectedly?

### ISSUE THREAD

**Issue by mockitoguy** [mockito/shipkit#781]
I haven't dug deeper so it may be a red herring. Mockito build did not complete the release because the tag already existed: https://github.com/mockito/mockito/issues/1637

**Comment by epeee** [comment]
It looks like a tag is already created by creating the release on github via rest, isn't it?

see 

https://github.com/mockito/shipkit/blob/93f8d485a2ace57c1ad6afcfe87cbaa9104a802d/subprojects/shipkit/src/main/groovy/org/shipkit/internal/gradle/notes/tasks/UpdateReleaseNotesOnGitHub.java#L56-L77

and

https://developer.github.com/v3/repos/releases/#create-a-release

we have two options:

- do not create a tag in our plugins since it looks like the tag is created during rest calls of creating a new release

- we change the order: push the changes first and create the release via rest afterwards. Doing so the tag created via our plugin will be reused (see rest api doc)

**Comment by mstachniuk** [comment]
The git tag was always created BEFORE upload to Bintray, because it's easier to undo git tag instead of release in Bintray / Maven Central.
And yes - upload release notes on GitHub needs to be done after creating and push the tag.
In shipkit-example it works: https://travis-ci.org/mockito/shipkit-example/jobs/497595910#L831
but the order of task execution is different.
So the task `updateReleaseNotesOnGitHub` should depend on `gitPush`

**Comment by epeee** [comment]
:+1: yep, let's fix the task execution order.
